# Generated by Django 5.2.17 on 2026-09-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
    ]
